name: pull-request-workflow
on: issues
jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo 11111111111
        echo 2222222222222
